pure_pursuit_node:
  ros__parameters:
    path_topic: "/planning/path"
    cmd_topic: "/cmd"
    lookahead_marker_topic: "/planning/lookahead_marker"
    lookahead_distance: 3
    wheelbase: 1.58
    target_speed: 3.0
    max_steering_angle: 0.52
    control_rate_hz: 20.0
    path_timeout_sec: 0.2